{
 "title": "Validator Participation Rates Dashboardssss",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Target Participations Rates",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "beacon_network_target_participation",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Source Participations Rates",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "beacon_network_source_participation",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Head Participations Rates",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "beacon_network_head_participation",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Inactivity Scores",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "beacon_network_inactivity_scores",
     "legendFormat": "{{range}}"
    }
   ]
  }
 ]
}