{
 "title": "Dora Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "dora_cl_pool_clients{service=\"dora\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dora_cl_pool_clients_online{service=\"dora\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dora_cl_pool_clients_optimistic{service=\"dora\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dora_cl_pool_clients_syncing{service=\"dora\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "dora_el_pool_clients{service=\"dora\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dora_el_pool_clients_online{service=\"dora\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dora_el_pool_clients_syncing{service=\"dora\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  { "title": "Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{service=\"dora\"} - go_memstats_other_sys_bytes{service=\"dora\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{service=\"dora\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{service=\"dora\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"dora\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{service=\"dora\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{service=\"dora\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{service=\"dora\"} - go_memstats_frees_total{service=\"dora\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{service=\"dora\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "go_goroutines – number of go routines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{service=\"dora\"}"
    },
    {
     "expr": "go_threads{service=\"dora\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"dora\"}[1m])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"dora\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"dora\"}"
    }
   ]
  }
 ]
}