{
 "title": "FOCIL metrics",
 "description": "FOCIL metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": "grandine, lighthouse, lodestar, nimbus, prysm, teku, besu, erigon, geth, nethermind, reth"
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "sum_by",
    "label": "Sum by",
    "query": "job : job, source : job\\,source"
   }
  ]
 },
 "panels": [
  { "title": "Broadcasting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of published inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (12 * rate(beacon_inclusion_lists_published_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "12 * rate(beacon_inclusion_lists_published_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of received inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_lists_received_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Total number of transactions in received inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_list_transactions_received_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Inclusion list arrival time",
   "type": "heatmap",
   "description": "Inclusion list arrival time since the beginning of the slot",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(beacon_inclusion_lists_arrival_time_seconds_bucket{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total number of valid inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_lists_valid_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Size of valid inclusion lists (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_lists_valid_size_bytes_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_lists_invalid_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}} {{reason}}"
    }
   ]
  },
  {
   "title": "Size of invalid inclusion lists (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(beacon_inclusion_lists_invalid_size_bytes_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to validate inclusion list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by($sum_by) (histogram_quantile(0.99, rate(beacon_inclusion_lists_validation_time_seconds_bucket{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 } },
  { "title": "Fork choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total number of equivocating inclusion lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by ($sum_by) (12 * rate(beacon_inclusion_lists_equivocating_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Total number of unsatisfied inclusion list blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by ($sum_by) (12 * rate(beacon_inclusion_list_unsatisfied_blocks_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  { "title": "Engine API, Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "IL txns sent when notifying new payload per slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(12 * rate(beacon_inclusion_list_transactions_notify_new_payload_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "IL txns included into block per slot (verification)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(execution_inclusion_list_block_validation_transactions_included_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "IL txns excluded from block per slot (verification)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by($sum_by, reason) (12 * rate(execution_inclusion_list_block_validation_transactions_excluded_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{reason}}"
    }
   ]
  },
  {
   "title": "IL txns sent when preparing execution payload per slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "(12 * rate(beacon_inclusion_list_transactions_prepare_execution_payload_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "IL txns included into block per slot (block building)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by($sum_by) (12 * rate(execution_inclusion_list_block_building_transactions_included_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": " IL txns excluded from block per slot (block building)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum by($sum_by, reason) (12 * rate(execution_inclusion_list_block_building_transactions_excluded_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{reason}}"
    }
   ]
  },
  {
   "title": "engine_getInclusionListV1 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "12 * rate(beacon_engine_getInclusionListV1_requests_total{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "engine_getInclusionListV1 requests duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_engine_getInclusionListV1_requests_duration_seconds_bucket{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to validate block against inclusion list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "avg by($sum_by) (histogram_quantile(0.99, rate(execution_inclusion_list_block_validation_time_seconds_bucket{client_name=~\"$client\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}