{
 "title": "PeerDAS metrics",
 "description": "Beacon PeerDAS metrics according to the beacon metrics specs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": "lighthouse, teku, prysm, lodestar, grandine, nimbus"
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": "supernodes : True, full nodes : False"
   }
  ]
 },
 "panels": [
  { "title": "PeerDAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data column sidecars submitted for processing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (job) (increase(beacon_data_column_sidecar_processing_requests_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars verified for gossip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(beacon_data_column_sidecar_processing_successes_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Column processing failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(beacon_data_column_sidecar_processing_requests_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval])) - sum by(job) (increase(beacon_data_column_sidecar_processing_successes_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime of data column sidecars gossip verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_seconds_bucket            {client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 requests",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 requests to an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(beacon_engine_getBlobsV2_requests_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 responses",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 successful responses from an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(beacon_engine_getBlobsV2_responses_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 losses",
   "type": "timeseries",
   "description": "Count of engine_getBlobsV2 requests that did not receive an answer",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job)(increase(beacon_engine_getBlobsV2_requests_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))\n-\nsum by(job)(increase(beacon_engine_getBlobsV2_responses_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime of engine_getBlobsV2",
   "type": "timeseries",
   "description": " Full runtime of engine_getBlobsV2",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_engine_getBlobsV2_runtime_seconds_bucket{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_engine_getBlobsV2_runtime_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total count of reconstructed columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (job) (increase(beacon_data_availability_reconstructed_columns_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to reconstruct columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_seconds_bucket{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to compute data column sidecar",
   "type": "timeseries",
   "description": "Time taken to compute data column sidecar, including cells and inclusion proof",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_seconds_bucket{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify data column sidecar inclusion proof",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_seconds_bucket{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Runtime of batched data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_seconds_bucket{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_milliseconds_bucket{\n    client_name=~\"$client\",\n    job=~\"$job\",\n    supernode=~\"$nodes\"\n  }[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Custody groups (super nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups for super nodes",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups{client_name=~\"$client\", job=~\"$job\", supernode=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custody groups (full nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups for full nodes",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups{client_name=~\"$client\", job=~\"$job\", supernode=\"False\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (super nodes)",
   "type": "bargauge",
   "description": "Total number of backfilled custody groups for super nodes",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{client_name=~\"$client\", job=~\"$job\", supernode=\"True\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (full nodes)",
   "type": "bargauge",
   "description": "Total number of backfilled custody groups for full nodes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{client_name=~\"$client\", job=~\"$job\", supernode=\"False\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gossipsub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Number of gossip messages sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_sent_counts_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (including duplicates)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_counts_unfiltered_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (deduplicated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_counts_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_sent_bytes_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes received from each topic (including duplicates)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_bytes_unfiltered_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes received from each topic (deduplicated) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_bytes_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Req/Resp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Number of requests sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_requests_sent_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_requests_received_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_responses_sent_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_responses_received_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_requests_bytes_sent_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests bytes received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_requests_bytes_received_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_responses_bytes_sent_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses bytes received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(libp2p_rpc_responses_bytes_received_total{client_name=~\"$client\", job=~\"$job\", supernode=~\"$nodes\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}