{
 "title": "Vero - Detailed",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vero_info,instance)"
    }
   },
   {
    "name": "beacon_node_host",
    "label": "Beacon Node",
    "query": {
     "query": "label_values(requests_created{service_type=\"beacon_node\", instance=\"$instance\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Published blocks [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_blocks_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published attestations [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_attestations_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published sync messages [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_sync_committee_messages_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published aggregate attestations [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_aggregate_attestations_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published sync contributions [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_sync_committee_contributions_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Consensus Time [$__interval] - 99% quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "99% quantile"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_status{instance=\"$instance\", status!=\"other\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "validator_status{instance=\"$instance\", status=\"other\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Attestation Consensus Failures [1h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_attestation_consensus_failures_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slashing Detection Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slashing_detected{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(errors_total{instance=\"$instance\"}[1h])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vero_info{instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Beacon Node Score",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "beacon_node_score{instance=\"$instance\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Attestation Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation Consensus Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "50% quantile"
      },
      {
       "expr": "histogram_quantile(0.8, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "80% quantile"
      },
      {
       "expr": "histogram_quantile(0.9, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "90% quantile"
      },
      {
       "expr": "histogram_quantile(0.99, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "100% quantile"
      }
     ]
    },
    {
     "title": "Attestation Consensus Time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(vc_attestation_consensus_time_bucket{le!=\"+Inf\", instance=\"$instance\"}[$__range])\n/ ignoring(le) group_left\nrate(vc_attestation_consensus_time_bucket{le=\"+Inf\", instance=\"$instance\"}[$__range])",
       "legendFormat": "{{ le }}s"
      }
     ]
    },
    {
     "title": "Attestation Consensus Time",
     "type": "heatmap",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(rate(vc_attestation_consensus_time_bucket{instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duty Start Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "block-proposal",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_start_time_sum{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval])\n/\nrate(duty_start_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "attestation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_start_time_sum{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval])\n/\nrate(duty_start_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "sync-committee-message",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_start_time_sum{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval])\n/\nrate(duty_start_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "attestation-aggregation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_start_time_sum{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval])\n/\nrate(duty_start_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "sync-committee-contribution",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_start_time_sum{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval])\n/\nrate(duty_start_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_start_time_bucket{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "block-proposal",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(duty_start_time_bucket{duty=\"block-proposal\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "attestation",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 4, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(duty_start_time_bucket{duty=\"attestation\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "sync-committee-message",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 9, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(duty_start_time_bucket{duty=\"sync-committee-message\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "attestation-aggregation",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 14, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(duty_start_time_bucket{duty=\"attestation-aggregation\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "sync-committee-contribution",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 19, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(duty_start_time_bucket{duty=\"sync-committee-contribution\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duty Submission Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "block-proposal",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_submission_time_sum{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval])\n/\nrate(duty_submission_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"block-proposal\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "attestation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_submission_time_sum{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval])\n/\nrate(duty_submission_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"attestation\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "sync-committee-message",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_submission_time_sum{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval])\n/\nrate(duty_submission_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"sync-committee-message\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "attestation-aggregation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_submission_time_sum{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval])\n/\nrate(duty_submission_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"attestation-aggregation\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "sync-committee-contribution",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(duty_submission_time_sum{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval])\n/\nrate(duty_submission_time_count[$__rate_interval])",
       "legendFormat": "Mean"
      },
      {
       "expr": "histogram_quantile(0.99, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval]))",
       "legendFormat": "99% quantile"
      },
      {
       "expr": "histogram_quantile(1, rate(duty_submission_time_bucket{instance=\"$instance\", duty=\"sync-committee-contribution\"}[$__rate_interval]))",
       "legendFormat": "Max (estimate) <="
      }
     ]
    },
    {
     "title": "block-proposal",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 4, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(duty_submission_time_bucket{duty=\"block-proposal\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "attestation",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 4, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(duty_submission_time_bucket{duty=\"attestation\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "sync-committee-message",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 9, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(duty_submission_time_bucket{duty=\"sync-committee-message\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "attestation-aggregation",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 14, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(duty_submission_time_bucket{duty=\"attestation-aggregation\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "sync-committee-contribution",
     "type": "heatmap",
     "gridPos": { "h": 19, "w": 5, "x": 19, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(duty_submission_time_bucket{duty=\"sync-committee-contribution\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beacon node - $beacon_node_host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "beacon_node_host",
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "beacon_node_version{instance=\"$instance\", host=~\"$beacon_node_host\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Requests [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 10, "x": 4, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(requests_total{service_type=\"beacon_node\", host=~\"$beacon_node_host\", instance=\"$instance\"}[$__interval])) by (status, method, path)",
       "legendFormat": "{{status}} {{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 10, "x": 14, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(request_duration_seconds_sum{service_type=\"beacon_node\", host=~\"$beacon_node_host\", instance=\"$instance\"}[$__rate_interval])\n/\nrate(request_duration_seconds_count[$__rate_interval])",
       "legendFormat": "{{ status}} {{ method }} {{ path }}"
      }
     ]
    },
    {
     "title": "Score",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_node_score{instance=\"$instance\", host=~\"$beacon_node_host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed beacon node events [$__interval]",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "round(increase(vc_processed_beacon_node_events_total{instance=\"$instance\", host=~\"$beacon_node_host\"}[$__interval])) > 0",
       "legendFormat": "{{ event_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote signer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signing Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(request_duration_seconds_sum{service_type=\"remote_signer\", instance=\"$instance\", request_type!=\"None\"}[$__rate_interval])\n/\nrate(request_duration_seconds_count[$__rate_interval])",
       "legendFormat": "{{ request_type }}"
      }
     ]
    },
    {
     "title": "Requests [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(requests_total{service_type=\"remote_signer\", instance=\"$instance\"}[$__interval])) by (status, method, path)",
       "legendFormat": "{{status}} {{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Signed Messages [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(signed_messages_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{ signable_message_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors [$__interval]",
     "type": "status-history",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "round(increase(errors_total{instance=\"$instance\"}[$__interval]))",
       "legendFormat": "{{ error_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage - rate (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) and on(instance, job) vero_info",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "CPU Usage - irate (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) and on(instance, job) vero_info",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Resident Memory (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"} and on(instance, job) vero_info",
       "legendFormat": "Resident Memory"
      }
     ]
    },
    {
     "title": "Uptime (Main Process)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=\"$instance\"} and on(instance, job) vero_info",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Loop Lag - 99% quantile (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(event_loop_lag_seconds_bucket{instance=\"$instance\"}[$__rate_interval])) and on(instance, job) vero_info",
       "legendFormat": "{{ time_since_slot_start }}s into slot"
      }
     ]
    },
    {
     "title": "Event Loop Tasks (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "event_loop_tasks{instance=\"$instance\"} and on(instance, job) vero_info",
       "legendFormat": "Tasks"
      }
     ]
    },
    {
     "title": "GC Objects Collected (Main Process)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{instance=\"$instance\"}[$__rate_interval]) and on(instance, job) vero_info",
       "legendFormat": "Generation {{ generation }}"
      }
     ]
    }
   ]
  }
 ]
}