{
 "title": "Lighthouse PeerDAS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Data Column Sidecar & KZG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data column sidecars submitted for processing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(beacon_blobs_column_sidecar_processing_requests_total{job=~\"$job\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars verified for gossip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(beacon_blobs_column_sidecar_processing_successes_total{job=~\"$job\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Column processing failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(beacon_blobs_column_sidecar_processing_requests_total{job=~\"$job\"}[$__interval])) - sum by(job) (increase(beacon_blobs_column_sidecar_processing_successes_total{job=~\"$job\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken to compute data column sidecar",
   "type": "timeseries",
   "description": "Time taken to compute data column sidecar, including cells, proofs and inclusion proof",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(data_column_sidecar_computation_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify data column sidecar inclusion proof",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(data_column_sidecar_inclusion_proof_verification_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total count of reconstructed columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (increase(data_availability_reconstructed_columns_total{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to reconstruct columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(data_availability_reconstruction_time_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Runtime of single data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kzg_verification_data_column_single_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Runtime of batched data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kzg_verification_data_column_batch_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Full runtime of data column sidecars gossip verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_blobs_column_sidecar_gossip_verification_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of gossip messages sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_sent_counts_total{job=~\"$job\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (duplicates)",
   "type": "timeseries",
   "description": "Number of gossip messages received from each topic (including duplicates)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_counts_unfiltered_total{job=~\"$job\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (deduplicated)",
   "type": "timeseries",
   "description": "Number of gossip messages received from each topic (deduplicated)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_counts_total{job=~\"$job\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_sent_bytes_total{job=~\"$job\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes received from each topic (duplicates)",
   "type": "timeseries",
   "description": "Number of bytes received from each topic (including duplicates) ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(gossipsub_topic_msg_recv_bytes_total{job=~\"$job\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}