{
 "title": "Fork Choice",
 "tags": [ "lighthouse" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Fork Choice Metrics\n\nMetrics collected regarding the LMD GHOST fork choice function.\n\nInvovles the `BeaconChain` analysing all non-finalized fork blocks and choosing a winning head block. Utilizes the \"reduced tree\" fork choice method.\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) and [`lmd_ghost`](https://github.com/sigp/lighthouse/tree/master/eth2/lmd_ghost) crates.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Full Fork Choice Runtime",
   "type": "timeseries",
   "description": "The `BeaconChain::fork_choice` function.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum[5m])\n/\nrate(beacon_fork_choice_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Core find_head() function\n\n\nThe core function which reads the block tree and finds a winning block.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 15, "y": 6 },
   "options": {
    "content": "\n### Usage rates (per minute)\n\n\nRequests, head changes and re-org count."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Core find_head() Function",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_find_head_seconds_sum[5m])\n/\nrate(beacon_fork_choice_find_head_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Fork Choice Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(beacon_fork_choice_requests_total [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 14 },
   "options": {
    "content": "\n### Block fork-choice processing times\n\n\nThe time it takes to update the fork-choice block-graph with a block (and all included attestations). Does not find the head.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Changes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(beacon_fork_choice_changed_head_total [1m])"
    }
   ]
  },
  {
   "title": "Fork Choice Process Block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_process_block_seconds_sum[5m])\n/\nrate(beacon_fork_choice_process_block_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Re-orgs per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(beacon_fork_choice_reorg_total [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 22 },
   "options": {
    "content": "\n### Attestation fork-choice processing times\n\n\nThe time it takes to update the fork-choice block-graph with an attestation, which may come in a block, from the network or other source.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fork Choice Process Attestation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_process_attestation_seconds_sum[5m])\n/\nrate(beacon_fork_choice_process_attestation_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 26 },
   "content": "\n### Excess find_head() rate.\n\n\nTracks the ratio between calls to `find_head()` that change the head and those that don't. A rate of `1` is theoretically ideal, less means we called `find_head` when we had no new information that would cause a change.",
   "targets": [
    {}
   ]
  },
  {
   "title": "Fork Choice Waste Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_fork_choice_requests_total [1m]) / increase(beacon_fork_choice_changed_head_total [1m])"
    }
   ]
  },
  {
   "title": "Balance Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_balances_cache_hits_total"
    }
   ]
  },
  {
   "title": "Balance Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_balances_cache_misses_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 35 },
   "content": "\n### Head Updating\n\nDistinct from actually finding the head, these metrics track how long it takes the update the BeaconChain head once a new one has been found (or not)",
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_database_read_seconds_sum[1m])\n/\nrate(beacon_fork_choice_database_read_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Inspect New Head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_inspect_new_head_seconds_sum[1m])\n/\nrate(beacon_fork_choice_inspect_new_head_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Prepare New Head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_prepare_new_head_seconds_sum[1m])\n/\nrate(beacon_fork_choice_prepare_new_head_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Update Canonical Head RwLock",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_update_head_seconds_sum[1m])\n/\nrate(beacon_update_head_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Persist BeaconChain to DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_persist_chain_sum[1m])\n/\nrate(beacon_persist_chain_count[1m])"
    }
   ]
  },
  {
   "title": "Run Post-Finalization Routines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_after_finalization_sum[1m])\n/\nrate(beacon_after_finalization_count[1m])"
    }
   ]
  }
 ]
}