{
 "title": "Sync",
 "tags": [ "lighthouse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Peers per sync status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sync_peers_per_status", "legendFormat": "{{sync_status}}" }
   ]
  },
  {
   "title": "Syncing chain counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sync_range_chains", "legendFormat": "{{range_type}}" }
   ]
  },
  {
   "title": "Lighthouse Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_loadavg_1", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Sync slots per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sync_slots_per_second", "legendFormat": " " }
   ]
  }
 ]
}