name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 'latest'
  warmup:
    description: 'Warmup kurtosis cache'
    required: false
    default: 'true'
  warmup_only:
    description: 'Warmup kurtosis cache, but do not load existing cache'
    required: false
    default: 'false'
  cache_prefix:
    description: 'Kurtosis cache prefix'
    required: false
    default: 'kurtosis-docker'
  s3_access_key:
    description: 'S3 access key'
    required: false
  s3_secret_key:
    description: 'S3 secret key'
    required: false
  s3_bucket:
    description: 'S3 bucket'
    required: false
  s3_endpoint:
    description: 'S3 endpoint'
    required: false
    default: 's3.amazonaws.com'
  s3_insecure:
    description: 'S3 secure'
    required: false
    default: 'false'
  s3_path:
    description: 'S3 path'
    required: false
    default: ''
outputs:
  kurtosis_version:
    description: "Kurtosis version"
    value: ${{ steps.cache.outputs.kurtosis_version }}
  cache_hit:
    description: "Cache hit"
    value: ${{ steps.cache.outputs.cache_hit }}
  cachedir:
    description: "Cachedir"
    value: ${{ steps.cache.outputs.cachedir }}
runs:
  using: composite
  steps:
    - name: Setup Kurtosis with docker cache
      continue-on-error: true
      id: cache
      uses: ethpandaops/kurtosis-cache-github-action@v1 # v1
      with:
        kurtosis_version: ${{ inputs.version }}
        warmup_cache: ${{ inputs.warmup }}
        warmup_only: ${{ inputs.warmup_only }}
        cache_prefix: ${{ inputs.cache_prefix }}
        s3_access_key: ${{ inputs.s3_access_key }}
        s3_secret_key: ${{ inputs.s3_secret_key }}
        s3_bucket: ${{ inputs.s3_bucket }}
        s3_endpoint: ${{ inputs.s3_endpoint }}
        s3_insecure: ${{ inputs.s3_insecure }}
        s3_path: ${{ inputs.s3_path }}

    - name: Setup kurtosis-cli
      if: ${{ inputs.warmup_only == 'false' }}
      shell: bash
      run: |
        if [ -z "$(which kurtosis)" ]; then
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli=${{ inputs.version }}
        fi
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH

        # Get the installed version and save it as an environment variable
        KURTOSIS_VERSION=$(kurtosis version | grep -o 'Version:[[:space:]]*[^[:space:]]*' | cut -d':' -f2 | tr -d ' ')
        echo "KURTOSIS_VERSION=$KURTOSIS_VERSION" >> $GITHUB_ENV
        echo "Installed Kurtosis version: $KURTOSIS_VERSION"
