name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 'latest'
  warmup:
    description: 'Warmup kurtosis cache'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Setup kurtosis-cli
      id: kurtosis_version
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        if [ "${{ inputs.version }}" = "latest" ]; then
          sudo apt install kurtosis-cli
        else
          sudo apt install kurtosis-cli=${{ inputs.version }}
        fi
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH

        # Get the installed version and save it as an environment variable
        KURTOSIS_VERSION=$(kurtosis version | grep -o 'Version:[[:space:]]*[^[:space:]]*' | cut -d':' -f2 | tr -d ' ')
        echo "KURTOSIS_VERSION=$KURTOSIS_VERSION" >> $GITHUB_ENV
        echo "version=$KURTOSIS_VERSION" >> $GITHUB_OUTPUT
        echo "Installed Kurtosis version: $KURTOSIS_VERSION"

    - name: Setup Kurtosis with docker cache
      continue-on-error: true
      id: testnet
      uses: ethpandaops/kurtosis-cache-github-action@v1 # v1
      with:
        kurtosis_version: ${{ steps.kurtosis_version.outputs.version }}
        warmup_cache: ${{ inputs.warmup }}
       