name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: '1.3.1'
runs:
  using: composite
  steps:
    - name: Install kurtosis
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=$VERSION
        kurtosis analytics disable
