name: Docker login
description: Log in to Docker Hub
inputs:
  username:
     required: true
  password:
     required: true
runs:
  using: composite
  steps:
    - name: Check for Docker Hub credentials
      shell: bash
      env:
        DOCKER_USERNAME: ${{ inputs.username }}
        DOCKER_PASSWORD: ${{ inputs.password }}
      run: |
        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
          echo "AUTH_EXISTS=false" >> $GITHUB_ENV
          echo "No credentials provided"
        else
          echo "AUTH_EXISTS=true" >> $GITHUB_ENV
          echo "Credentials provided"
        fi

    - name: Login to Docker Hub
      if: env.AUTH_EXISTS == 'true'
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Install regctl
      uses: regclient/actions/regctl-installer@1b705e32d40851370799ea5814e83d0a5f6a70dc # v0.1.0

    - name: Check Docker Hub Rate Limits
      shell: bash
      run: regctl image ratelimit ubuntu:latest
