name: Check typos

on:
  pull_request:
    branches:
      - main

jobs:
  check-typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check for typos
        uses: crate-ci/typos@a8d8e187146634c459c27ade2d3e338569378720 # v1.44.0
