on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.PAT }}
          release-type: simple
          include-v-in-tag: false
          package-name: ethereum-package
